/**
 * Codegen entrypoint. Two modes:
 *
 * 1. `OPENAPI_SPEC` env var points at a local JSON file — use that.
 *    The CI step + the offline workflow set this so we don't need a
 *    Cargo toolchain on the codegen runner.
 * 2. Otherwise spawn the `starstats-server-openapi` Cargo bin to dump
 *    the spec to a temp file and read it back. Falls through to the
 *    same parser, so the generated output is byte-identical regardless
 *    of source.
 *
 * Output lands at `src/generated/schema.ts`. The file is committed —
 * codegen is a build-time step but the artifact is part of the
 * package contract so consumers never have to run Cargo just to
 * `pnpm install`.
 */

import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PKG_ROOT = resolve(__dirname, '..');
const OUT = join(PKG_ROOT, 'src', 'generated', 'schema.ts');

function loadSpecJson(): string {
  const fromEnv = process.env.OPENAPI_SPEC;
  if (fromEnv && existsSync(fromEnv)) {
    return readFileSync(fromEnv, 'utf8');
  }

  const repoRoot = resolve(PKG_ROOT, '..', '..');
  const specPath = join(tmpdir(), 'starstats-openapi.json');
  const result = spawnSync(
    'cargo',
    [
      'run',
      '--quiet',
      '-p',
      'starstats-server',
      '--bin',
      'starstats-server-openapi',
    ],
    {
      cwd: repoRoot,
      encoding: 'utf8',
      // Buffer the JSON in stdout. utoipa keeps the spec well under
      // 1 MB, so the default Node buffer is fine.
      maxBuffer: 16 * 1024 * 1024,
    },
  );
  if (result.status !== 0) {
    process.stderr.write(result.stderr ?? '');
    throw new Error(
      `cargo run --bin starstats-server-openapi exited with code ${result.status}`,
    );
  }
  writeFileSync(specPath, result.stdout, 'utf8');
  return result.stdout;
}

async function main(): Promise<void> {
  const specJson = loadSpecJson();
  const spec = JSON.parse(specJson) as Record<string, unknown>;

  const ast = await openapiTS(spec, {
    additionalProperties: false,
  });
  const ts = astToString(ast);

  const banner =
    `/**\n` +
    ` * AUTO-GENERATED by packages/api-client-ts/scripts/generate.ts.\n` +
    ` * DO NOT EDIT BY HAND. Regenerate with \`pnpm --filter api-client-ts run generate\`.\n` +
    ` * Source: starstats-server OpenAPI spec.\n` +
    ` */\n\n`;

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, banner + ts, 'utf8');
  process.stderr.write(`wrote ${OUT}\n`);
}

main().catch((err) => {
  process.stderr.write(`${(err as Error).stack ?? err}\n`);
  process.exit(1);
});
