'use client';

import { useEffect } from 'react';
import Link from 'next/link';
import type { Route } from 'next';
import { usePathname } from 'next/navigation';

interface NavItem {
  label: string;
  href: Route;
  match?: (pathname: string) => boolean;
  /**
   * Optional count rendered as a small badge after the label. Used
   * for surfacing inbound state (e.g. # of people sharing with you)
   * so the user notices without having to visit the page. Hidden
   * when undefined or 0 so the rail stays calm for users with no
   * activity.
   */
  badge?: number;
}

interface NavSection {
  title: string;
  items: NavItem[];
}

interface Props {
  handle: string | null;
  /**
   * Site-wide staff grants for the current user (e.g. `["moderator"]`,
   * `["admin"]`). Mirrored from `/v1/auth/me` into the session cookie
   * at sign-in. We only render the Admin link when the user holds at
   * least one role; the actual /admin route enforces the same check
   * server-side, so this is purely a UX gate.
   */
  staffRoles: string[];
  /**
   * Number of inbound shares (people who have shared their manifest
   * with the current user). Rendered as a badge on the Sharing nav
   * entry so users notice new shares without having to visit the
   * page. Optional — undefined or 0 hides the badge.
   */
  inboundShareCount?: number;
}

const SETTINGS_2FA = '/settings/2fa';

function buildNav(
  handle: string | null,
  staffRoles: string[],
  inboundShareCount: number,
): NavSection[] {
  const profileHref = (
    handle ? `/u/${encodeURIComponent(handle)}` : '/settings'
  ) as Route;
  const isStaff = staffRoles.length > 0;
  return [
    // Insights — the user's own data surfaces. "Manifest" is the
    // dashboard landing; the rest drill into different cuts of the
    // same event stream.
    {
      title: 'Insights',
      items: [
        { label: 'Manifest', href: '/dashboard' },
        {
          label: 'Journey',
          // Typed routes manifest is regenerated by `next build`; until
          // that runs the new path isn't in `Route`. Cast away the
          // mismatch — same approach the codebase uses for other
          // dynamic / freshly-added paths (see LocationPill, donate).
          href: '/journey' as Route,
          match: (p) => p === '/journey' || p.startsWith('/journey/'),
        },
        {
          label: 'Metrics',
          href: '/metrics',
          match: (p) => p === '/metrics' || p.startsWith('/metrics/'),
        },
        {
          // Typed routes manifest is regenerated by `next build`; until
          // that runs the renamed path isn't in `Route` (was '/my-logs').
          // Same cast pattern as /journey and /lore above.
          label: 'Uploads',
          href: '/uploads' as Route,
          match: (p) => p === '/uploads' || p.startsWith('/uploads/'),
        },
      ],
    },
    // Community — outward-facing surfaces (profile pages, org rosters,
    // user-submitted reference fixes).
    {
      title: 'Community',
      items: [
        {
          label: 'Profile',
          href: profileHref,
          match: (p) => p.startsWith('/u/'),
        },
        {
          label: 'Orgs',
          href: '/orgs',
          match: (p) => p === '/orgs' || p.startsWith('/orgs/'),
        },
        {
          // Typed routes manifest is regenerated by `next build`; until
          // that runs the new path isn't in `Route`. Same cast pattern
          // used for /journey and /uploads above.
          label: 'Sharing',
          href: '/sharing' as Route,
          match: (p) => p === '/sharing' || p.startsWith('/sharing/'),
          badge: inboundShareCount > 0 ? inboundShareCount : undefined,
        },
        {
          label: 'Submissions',
          href: '/submissions',
          match: (p) => p === '/submissions' || p.startsWith('/submissions/'),
        },
      ],
    },
    // Setup — one-off configuration surfaces the user visits rarely.
    {
      title: 'Setup',
      items: [
        {
          label: 'Devices',
          href: '/devices',
          match: (p) => p === '/devices' || p.startsWith('/devices/'),
        },
        {
          label: 'Lore',
          // Typed routes manifest is regenerated by `next build`; until
          // that runs the new path isn't in `Route`. Same cast pattern
          // used for /journey above.
          href: '/lore' as Route,
          match: (p) => p === '/lore' || p.startsWith('/lore/'),
        },
        {
          label: 'Donate',
          href: '/donate',
          match: (p) => p === '/donate' || p.startsWith('/donate/'),
        },
      ],
    },
    {
      title: 'Account',
      items: [
        {
          label: 'Settings',
          href: '/settings',
          match: (p) => p === '/settings',
        },
        { label: 'Two-factor', href: SETTINGS_2FA },
      ],
    },
    // Staff section — only present when the user holds a moderator or
    // admin grant. The Admin route runs its own server-side gate so
    // this is purely a UX affordance.
    ...(isStaff
      ? [
          {
            title: 'Staff',
            items: [
              {
                label: 'Admin',
                href: '/admin' as Route,
                match: (p: string) => p === '/admin' || p.startsWith('/admin/'),
              },
            ],
          },
        ]
      : []),
  ];
}

function isActive(item: NavItem, pathname: string): boolean {
  if (item.match) return item.match(pathname);
  return pathname === item.href;
}

export function LeftRail({ handle, staffRoles, inboundShareCount = 0 }: Props) {
  const pathname = usePathname() ?? '';
  const sections = buildNav(handle, staffRoles, inboundShareCount);

  // Mobile drawer leaks across soft-navigations: clicking a nav link
  // closes the rail visually but leaves `body[data-drawer="open"]` set,
  // so the next page mounts with a "stuck open" rail. Clear on every
  // pathname change. Runs server-side too but `document` is gated.
  useEffect(() => {
    if (typeof document !== 'undefined') {
      delete document.body.dataset.drawer;
    }
  }, [pathname]);

  return (
    <aside className="ss-rail" aria-label="Primary navigation">
      {sections.map((section) => (
        <div key={section.title}>
          <div className="ss-rail-section">{section.title}</div>
          {section.items.map((item) => {
            const active = isActive(item, pathname);
            return (
              <Link
                key={item.href + item.label}
                href={item.href}
                className="ss-rail-item"
                data-active={active ? 'true' : undefined}
                style={{ textDecoration: 'none' }}
              >
                <span className="ss-rail-dot" aria-hidden="true" />
                <span style={{ flex: 1 }}>{item.label}</span>
                {item.badge !== undefined && item.badge > 0 && (
                  <span
                    className="ss-rail-badge"
                    aria-label={`${item.badge} new`}
                  >
                    {item.badge > 99 ? '99+' : item.badge}
                  </span>
                )}
              </Link>
            );
          })}
        </div>
      ))}
      <div className="ss-rail-footer">
        <a href="/auth/logout">Sign out</a>
      </div>
    </aside>
  );
}
