'use client';

import { useEffect } from 'react';
import Link from 'next/link';
import type { Route } from 'next';
import { usePathname } from 'next/navigation';

interface NavItem {
  label: string;
  href: Route;
  match?: (pathname: string) => boolean;
}

interface NavSection {
  title: string;
  items: NavItem[];
}

interface Props {
  handle: string | null;
}

const SETTINGS_2FA = '/settings/2fa';

function buildNav(handle: string | null): NavSection[] {
  const profileHref = (
    handle ? `/u/${encodeURIComponent(handle)}` : '/settings'
  ) as Route;
  return [
    {
      title: 'Main',
      items: [
        { label: 'Manifest', href: '/dashboard' },
        {
          label: 'Journey',
          // Typed routes manifest is regenerated by `next build`; until
          // that runs the new path isn't in `Route`. Cast away the
          // mismatch — same approach the codebase uses for other
          // dynamic / freshly-added paths (see LocationPill, donate).
          href: '/journey' as Route,
          match: (p) => p === '/journey' || p.startsWith('/journey/'),
        },
        {
          label: 'Metrics',
          href: '/metrics',
          match: (p) => p === '/metrics' || p.startsWith('/metrics/'),
        },
        {
          label: 'My logs',
          href: '/my-logs',
          match: (p) => p === '/my-logs' || p.startsWith('/my-logs/'),
        },
        {
          label: 'Submissions',
          href: '/submissions',
          match: (p) => p === '/submissions' || p.startsWith('/submissions/'),
        },
        {
          label: 'Donate',
          href: '/donate',
          match: (p) => p === '/donate' || p.startsWith('/donate/'),
        },
        {
          label: 'Hangar',
          href: '/devices',
          match: (p) => p === '/devices' || p.startsWith('/devices/'),
        },
        {
          label: 'Orgs',
          href: '/orgs',
          match: (p) => p === '/orgs' || p.startsWith('/orgs/'),
        },
        {
          label: 'Profile',
          href: profileHref,
          match: (p) => p.startsWith('/u/'),
        },
      ],
    },
    {
      title: 'Account',
      items: [
        {
          label: 'Settings',
          href: '/settings',
          match: (p) => p === '/settings',
        },
        { label: 'Two-factor', href: SETTINGS_2FA },
      ],
    },
  ];
}

function isActive(item: NavItem, pathname: string): boolean {
  if (item.match) return item.match(pathname);
  return pathname === item.href;
}

export function LeftRail({ handle }: Props) {
  const pathname = usePathname() ?? '';
  const sections = buildNav(handle);

  // Mobile drawer leaks across soft-navigations: clicking a nav link
  // closes the rail visually but leaves `body[data-drawer="open"]` set,
  // so the next page mounts with a "stuck open" rail. Clear on every
  // pathname change. Runs server-side too but `document` is gated.
  useEffect(() => {
    if (typeof document !== 'undefined') {
      delete document.body.dataset.drawer;
    }
  }, [pathname]);

  return (
    <aside className="ss-rail" aria-label="Primary navigation">
      {sections.map((section) => (
        <div key={section.title}>
          <div className="ss-rail-section">{section.title}</div>
          {section.items.map((item) => {
            const active = isActive(item, pathname);
            return (
              <Link
                key={item.href + item.label}
                href={item.href}
                className="ss-rail-item"
                data-active={active ? 'true' : undefined}
                style={{ textDecoration: 'none' }}
              >
                <span className="ss-rail-dot" aria-hidden="true" />
                <span>{item.label}</span>
              </Link>
            );
          })}
        </div>
      ))}
      <div className="ss-rail-footer">
        <a href="/auth/logout">Sign out</a>
      </div>
    </aside>
  );
}
